# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "theme-app-extension"
client_id = "a83d9a1af3cbccb4882ef8d59bbcb341"
application_url = "https://backed-morning-conduct-exports.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://backed-morning-conduct-exports.trycloudflare.com/auth/callback",
  "https://backed-morning-conduct-exports.trycloudflare.com/auth/shopify/callback",
  "https://backed-morning-conduct-exports.trycloudflare.com/api/auth/callback",
  "https://backed-morning-conduct-exports.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shoesstore13.myshopify.com"
